# Generated by Django 5.1.4 on 2025-01-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=5, help_text='Price of book in this format:123.45', max_digits=8),
        ),
    ]
